import Head from 'next/head'
import { Header, Main, Sidebar, Footer } from '../components';



export default function Home() {
  return (
    <div className='container flex h-screen bg-green-300'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex-1 flex flex-col overflow-hidden' >
        <Header />
        <Main />
        <Sidebar />
        <Footer />
      </main>
    </div>
  )
}
